### ISSUE TITLE
TypeError: config.transforms[index] is not a function

### ISSUE THREAD

**Issue by AlonMiz** [syntax-tree/mdast-util-from-markdown#14] opened 2021-02-03 14:30 UTC
### Subject of the issue
Failing unit tests when using react-markdown which using this library

```
   ● Some test with react-markdown in jest using testing-library
     TypeError: config.transforms[index] is not a function
   
at compile (../node_modules/mdast-util-from-markdown/dist/index.js:226:38)
at fromMarkdown (../node_modules/mdast-util-from-markdown/dist/index.js:24:27)
at parse (../node_modules/remark-parse/index.js:13:12)
at Function.parse (../node_modules/unified/index.js:284:12)
at ReactMarkdown (../node_modules/react-markdown/lib/react-markdown.js:42:42)
at renderWithHooks (../node_modules/react-dom/cjs/react-dom.development.js:16260:18)
at mountIndeterminateComponent (../node_modules/react-dom/cjs/react-dom.development.js:18794:13)
at beginWork$1 (../node_modules/react-dom/cjs/react-dom.development.js:20162:16)
at HTMLUnknownElement.callCallback (../node_modules/react-dom/cjs/react-dom.development.js:336:14)
at invokeEventListeners (../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
at HTMLUnknownElementImpl._dispatch (../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
at HTMLUnknownElementImpl.dispatchEvent (../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
at HTMLUnknownElementImpl.dispatchEvent (../node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
at HTMLUnknownElement.dispatchEvent (../node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
at Object.invokeGuardedCallbackDev (../node_modules/react-dom/cjs/react-dom.development.js:385:16)
at invokeGuardedCallback (../node_modules/react-dom/cjs/react-dom.development.js:440:31)
at beginWork$$1 (../node_modules/react-dom/cjs/react-dom.development.js:25780:7)
at performUnitOfWork (../node_modules/react-dom/cjs/react-dom.development.js:24698:12)
at workLoopSync (../node_modules/react-dom/cjs/react-dom.development.js:24671:22)
at performSyncWorkOnRoot (../node_modules/react-dom/cjs/react-dom.development.js:24270:11)
at ../node_modules/react-dom/cjs/react-dom.development.js:12199:24
at unstable_runWithPriority (../node_modules/scheduler/cjs/scheduler.development.js:697:12)
at runWithPriority$2 (../node_modules/react-dom/cjs/react-dom.development.js:12149:10)
at flushSyncCallbackQueueImpl (../node_modules/react-dom/cjs/react-dom.development.js:12194:7)
at flushSyncCallbackQueue (../node_modules/react-dom/cjs/react-dom.development.js:12182:3)
at scheduleUpdateOnFiber (../node_modules/react-dom/cjs/react-dom.development.js:23709:9)
at dispatchAction (../node_modules/react-dom/cjs/react-dom.development.js:17076:5)

```

### Your environment

*   **OS**: Mac os
*   **Packages**: version "0.8.4"
*   **Env**: node 15, yarn 1.22, jest 26

### Steps to reproduce
rendering a markdown with react-markdown.
it works in our prod.
works when working locally with the unit tests
but it fails in our pipeline
so I'm really sorry that i cant reproduce that easily. but maybe that's enught for you to tackle or understand what's the issue or if mdast-util-from-markdown should handle that case

### Expected behavior
What should happen?
handle that case, without exploding or provide a better error explaining what went wrong

### Actual behavior
exploding on this code block
![image](https://user-images.githubusercontent.com/1812912/106760723-c428a100-663c-11eb-8826-8149178a7c7b.png)
https://github.com/syntax-tree/mdast-util-from-markdown/blob/16c95f55298acb90f69cd253601672eb78e1b4d4/lib/index.js#L225

**Comment by ChristianMurphy** [comment] 2021-02-03 14:52
@AlonMiz Could you share a runnable example of configuration and content that causes the issue?
I'm not able to reproduce the issue.
Here is a codesandbox which can be used as a starter: https://codesandbox.io/s/react-markdown-debug-9n4eg

**Comment by wooorm** [comment] 2021-02-03 15:03
Fixed already: rm -r node modules; npm install should do the trick!

**Comment by AlonMiz** [comment] 2021-02-03 15:49
@ChristianMurphy as I described, I couldn't reproduce it on my machine. it only happened in our pipeline inside a docker.
😞 sorry for that
@wooorm WDYM fixed already. the docker build is really atomic in how it builds and installs the packages.
I cannot simply remove and install again. does that error signifies something is broken with the dependency tree?

Thanks!

**Comment by wooorm** [comment] 2021-02-03 17:06
Yes, it was a release that was broken, and I published a patch!

**Comment by ChristianMurphy** [comment] 2021-02-03 18:01
> I described, I couldn't reproduce it on my machine. it only happened in our pipeline inside a docker.

Even so, a copy of the input and plugins where it fails in docker would still be helpful.
Though, as @wooorm, it sounds a lot like an older version may be getting installed.

> the docker build is really atomic in how it builds and installs the packages

If there is a _yarn.lock_, package-lock.json, or _npm-shrinkwrap.json_, even with an atomic install the versions would not change.
And `npm upgrade` or `yarn upgrade` would be needed for docker to pick up the changes.

**Comment by wooorm** [comment] 2021-02-03 18:47
Closing as this was fixed in https://github.com/syntax-tree/mdast-util-gfm/releases/tag/0.1.2

**Closed by wooorm** 2021-02-03 18:47 UTC
Labels: 🧘 status/waiting

**Comment by AlonMiz** [comment] 2021-02-03 18:55
so 0.8.5 will fix that? 🙏🏿

**Comment by wooorm** [comment] 2021-02-03 18:59
It does. It was released several hours ago. So clearing caches should do the trick.

**Comment by AlonMiz** [comment] 2021-02-03 19:03
Thanks, will try
