### ISSUE TITLE
Uncaught TypeError: Cannot set properties of undefined (setting 'inTable')

### ISSUE THREAD

**Issue by capaj** [syntax-tree/mdast-util-from-markdown#34] opened 2023-09-20 07:28 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.0.0

### Steps to reproduce

1. checkout https://github.com/capaj/authier-pm-web/tree/bump-deps-oct-2023 
2. run pnpm dev
3. navigate to http://localhost:5450/features

### Expected behavior

Does not crash on type error on this MD: https://github.com/capaj/authier-pm-web/blob/bump-deps-oct-2023/pages/features.md

### Actual behavior

```
Uncaught TypeError: Cannot set properties of undefined (setting 'inTable')
    at Object.enterTable (index.js:78:1)
    at compile (index.js:363:1)
    at fromMarkdown (index.js:193:1)
    at parser (index.js:18:24)
    at Function.parse (index.js:273:1)
    at ReactMarkdown (react-markdown.js:106:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at recoverFromConcurrentError (react-dom.development.js:25850:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:25750:1)
    at workLoop (scheduler.development.js:266:1)
    at flushWork (scheduler.development.js:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:1)
```

### Affected runtime and version

node 18

### Affected package manager and version

pnpm

### Affected OS and version

ubuntu 22.04

### Build and bundle tools

Next.js

**Comment by ChristianMurphy** [comment] 2023-09-20 09:13
Duplicate of https://github.com/remarkjs/remark-gfm/issues/57

**Comment by ChristianMurphy** [comment] 2023-09-20 09:13
A major version release is rolling out across all: `mdx`, `unified`, `remark`, `rehype`, and `micromark` packages.
This includes both type changes (static analysis error) and changes to the parser (potential runtime error) if the major versions are mismatched.

Hold on version 3 of remark-gfm, until the next major of react markdown is released

**Closed by ChristianMurphy** 2023-09-20 09:13 UTC
Labels: 🤞 phase/open
